name: Continuous Integration

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: make build
      - name: Show help
        run: make help
      - name: Run test
        run: make test
